
### add 5 sku to cart
POST http://localhost:8082/user/31337/cart/1076963
Content-Type: application/json

{
  "count": 5
}

### get list of a cart
GET http://localhost:8082/user/31337/cart
Content-Type: application/json


