// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package lomsservice

//go:generate minimock -i route256/loms/pkg/api/loms/v1.LomsClient -o loms_client_mock_test.go -n LomsClientMock -p lomsservice

import (
	context "context"
	mm_loms "route256/loms/pkg/api/loms/v1"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// LomsClientMock implements mm_loms.LomsClient
type LomsClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcOrderCancel          func(ctx context.Context, in *mm_loms.OrderCancelRequest, opts ...grpc.CallOption) (ep1 *emptypb.Empty, err error)
	funcOrderCancelOrigin    string
	inspectFuncOrderCancel   func(ctx context.Context, in *mm_loms.OrderCancelRequest, opts ...grpc.CallOption)
	afterOrderCancelCounter  uint64
	beforeOrderCancelCounter uint64
	OrderCancelMock          mLomsClientMockOrderCancel

	funcOrderCreate          func(ctx context.Context, in *mm_loms.OrderCreateRequest, opts ...grpc.CallOption) (op1 *mm_loms.OrderCreateResponse, err error)
	funcOrderCreateOrigin    string
	inspectFuncOrderCreate   func(ctx context.Context, in *mm_loms.OrderCreateRequest, opts ...grpc.CallOption)
	afterOrderCreateCounter  uint64
	beforeOrderCreateCounter uint64
	OrderCreateMock          mLomsClientMockOrderCreate

	funcOrderInfo          func(ctx context.Context, in *mm_loms.OrderInfoRequest, opts ...grpc.CallOption) (op1 *mm_loms.OrderInfoResponse, err error)
	funcOrderInfoOrigin    string
	inspectFuncOrderInfo   func(ctx context.Context, in *mm_loms.OrderInfoRequest, opts ...grpc.CallOption)
	afterOrderInfoCounter  uint64
	beforeOrderInfoCounter uint64
	OrderInfoMock          mLomsClientMockOrderInfo

	funcOrderPay          func(ctx context.Context, in *mm_loms.OrderPayRequest, opts ...grpc.CallOption) (ep1 *emptypb.Empty, err error)
	funcOrderPayOrigin    string
	inspectFuncOrderPay   func(ctx context.Context, in *mm_loms.OrderPayRequest, opts ...grpc.CallOption)
	afterOrderPayCounter  uint64
	beforeOrderPayCounter uint64
	OrderPayMock          mLomsClientMockOrderPay

	funcStocksInfo          func(ctx context.Context, in *mm_loms.StocksInfoRequest, opts ...grpc.CallOption) (sp1 *mm_loms.StocksInfoResponse, err error)
	funcStocksInfoOrigin    string
	inspectFuncStocksInfo   func(ctx context.Context, in *mm_loms.StocksInfoRequest, opts ...grpc.CallOption)
	afterStocksInfoCounter  uint64
	beforeStocksInfoCounter uint64
	StocksInfoMock          mLomsClientMockStocksInfo
}

// NewLomsClientMock returns a mock for mm_loms.LomsClient
func NewLomsClientMock(t minimock.Tester) *LomsClientMock {
	m := &LomsClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.OrderCancelMock = mLomsClientMockOrderCancel{mock: m}
	m.OrderCancelMock.callArgs = []*LomsClientMockOrderCancelParams{}

	m.OrderCreateMock = mLomsClientMockOrderCreate{mock: m}
	m.OrderCreateMock.callArgs = []*LomsClientMockOrderCreateParams{}

	m.OrderInfoMock = mLomsClientMockOrderInfo{mock: m}
	m.OrderInfoMock.callArgs = []*LomsClientMockOrderInfoParams{}

	m.OrderPayMock = mLomsClientMockOrderPay{mock: m}
	m.OrderPayMock.callArgs = []*LomsClientMockOrderPayParams{}

	m.StocksInfoMock = mLomsClientMockStocksInfo{mock: m}
	m.StocksInfoMock.callArgs = []*LomsClientMockStocksInfoParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLomsClientMockOrderCancel struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockOrderCancelExpectation
	expectations       []*LomsClientMockOrderCancelExpectation

	callArgs []*LomsClientMockOrderCancelParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockOrderCancelExpectation specifies expectation struct of the LomsClient.OrderCancel
type LomsClientMockOrderCancelExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockOrderCancelParams
	paramPtrs          *LomsClientMockOrderCancelParamPtrs
	expectationOrigins LomsClientMockOrderCancelExpectationOrigins
	results            *LomsClientMockOrderCancelResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockOrderCancelParams contains parameters of the LomsClient.OrderCancel
type LomsClientMockOrderCancelParams struct {
	ctx  context.Context
	in   *mm_loms.OrderCancelRequest
	opts []grpc.CallOption
}

// LomsClientMockOrderCancelParamPtrs contains pointers to parameters of the LomsClient.OrderCancel
type LomsClientMockOrderCancelParamPtrs struct {
	ctx  *context.Context
	in   **mm_loms.OrderCancelRequest
	opts *[]grpc.CallOption
}

// LomsClientMockOrderCancelResults contains results of the LomsClient.OrderCancel
type LomsClientMockOrderCancelResults struct {
	ep1 *emptypb.Empty
	err error
}

// LomsClientMockOrderCancelOrigins contains origins of expectations of the LomsClient.OrderCancel
type LomsClientMockOrderCancelExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmOrderCancel *mLomsClientMockOrderCancel) Optional() *mLomsClientMockOrderCancel {
	mmOrderCancel.optional = true
	return mmOrderCancel
}

// Expect sets up expected params for LomsClient.OrderCancel
func (mmOrderCancel *mLomsClientMockOrderCancel) Expect(ctx context.Context, in *mm_loms.OrderCancelRequest, opts ...grpc.CallOption) *mLomsClientMockOrderCancel {
	if mmOrderCancel.mock.funcOrderCancel != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by Set")
	}

	if mmOrderCancel.defaultExpectation == nil {
		mmOrderCancel.defaultExpectation = &LomsClientMockOrderCancelExpectation{}
	}

	if mmOrderCancel.defaultExpectation.paramPtrs != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by ExpectParams functions")
	}

	mmOrderCancel.defaultExpectation.params = &LomsClientMockOrderCancelParams{ctx, in, opts}
	mmOrderCancel.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmOrderCancel.expectations {
		if minimock.Equal(e.params, mmOrderCancel.defaultExpectation.params) {
			mmOrderCancel.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmOrderCancel.defaultExpectation.params)
		}
	}

	return mmOrderCancel
}

// ExpectCtxParam1 sets up expected param ctx for LomsClient.OrderCancel
func (mmOrderCancel *mLomsClientMockOrderCancel) ExpectCtxParam1(ctx context.Context) *mLomsClientMockOrderCancel {
	if mmOrderCancel.mock.funcOrderCancel != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by Set")
	}

	if mmOrderCancel.defaultExpectation == nil {
		mmOrderCancel.defaultExpectation = &LomsClientMockOrderCancelExpectation{}
	}

	if mmOrderCancel.defaultExpectation.params != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by Expect")
	}

	if mmOrderCancel.defaultExpectation.paramPtrs == nil {
		mmOrderCancel.defaultExpectation.paramPtrs = &LomsClientMockOrderCancelParamPtrs{}
	}
	mmOrderCancel.defaultExpectation.paramPtrs.ctx = &ctx
	mmOrderCancel.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmOrderCancel
}

// ExpectInParam2 sets up expected param in for LomsClient.OrderCancel
func (mmOrderCancel *mLomsClientMockOrderCancel) ExpectInParam2(in *mm_loms.OrderCancelRequest) *mLomsClientMockOrderCancel {
	if mmOrderCancel.mock.funcOrderCancel != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by Set")
	}

	if mmOrderCancel.defaultExpectation == nil {
		mmOrderCancel.defaultExpectation = &LomsClientMockOrderCancelExpectation{}
	}

	if mmOrderCancel.defaultExpectation.params != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by Expect")
	}

	if mmOrderCancel.defaultExpectation.paramPtrs == nil {
		mmOrderCancel.defaultExpectation.paramPtrs = &LomsClientMockOrderCancelParamPtrs{}
	}
	mmOrderCancel.defaultExpectation.paramPtrs.in = &in
	mmOrderCancel.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmOrderCancel
}

// ExpectOptsParam3 sets up expected param opts for LomsClient.OrderCancel
func (mmOrderCancel *mLomsClientMockOrderCancel) ExpectOptsParam3(opts ...grpc.CallOption) *mLomsClientMockOrderCancel {
	if mmOrderCancel.mock.funcOrderCancel != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by Set")
	}

	if mmOrderCancel.defaultExpectation == nil {
		mmOrderCancel.defaultExpectation = &LomsClientMockOrderCancelExpectation{}
	}

	if mmOrderCancel.defaultExpectation.params != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by Expect")
	}

	if mmOrderCancel.defaultExpectation.paramPtrs == nil {
		mmOrderCancel.defaultExpectation.paramPtrs = &LomsClientMockOrderCancelParamPtrs{}
	}
	mmOrderCancel.defaultExpectation.paramPtrs.opts = &opts
	mmOrderCancel.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmOrderCancel
}

// Inspect accepts an inspector function that has same arguments as the LomsClient.OrderCancel
func (mmOrderCancel *mLomsClientMockOrderCancel) Inspect(f func(ctx context.Context, in *mm_loms.OrderCancelRequest, opts ...grpc.CallOption)) *mLomsClientMockOrderCancel {
	if mmOrderCancel.mock.inspectFuncOrderCancel != nil {
		mmOrderCancel.mock.t.Fatalf("Inspect function is already set for LomsClientMock.OrderCancel")
	}

	mmOrderCancel.mock.inspectFuncOrderCancel = f

	return mmOrderCancel
}

// Return sets up results that will be returned by LomsClient.OrderCancel
func (mmOrderCancel *mLomsClientMockOrderCancel) Return(ep1 *emptypb.Empty, err error) *LomsClientMock {
	if mmOrderCancel.mock.funcOrderCancel != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by Set")
	}

	if mmOrderCancel.defaultExpectation == nil {
		mmOrderCancel.defaultExpectation = &LomsClientMockOrderCancelExpectation{mock: mmOrderCancel.mock}
	}
	mmOrderCancel.defaultExpectation.results = &LomsClientMockOrderCancelResults{ep1, err}
	mmOrderCancel.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmOrderCancel.mock
}

// Set uses given function f to mock the LomsClient.OrderCancel method
func (mmOrderCancel *mLomsClientMockOrderCancel) Set(f func(ctx context.Context, in *mm_loms.OrderCancelRequest, opts ...grpc.CallOption) (ep1 *emptypb.Empty, err error)) *LomsClientMock {
	if mmOrderCancel.defaultExpectation != nil {
		mmOrderCancel.mock.t.Fatalf("Default expectation is already set for the LomsClient.OrderCancel method")
	}

	if len(mmOrderCancel.expectations) > 0 {
		mmOrderCancel.mock.t.Fatalf("Some expectations are already set for the LomsClient.OrderCancel method")
	}

	mmOrderCancel.mock.funcOrderCancel = f
	mmOrderCancel.mock.funcOrderCancelOrigin = minimock.CallerInfo(1)
	return mmOrderCancel.mock
}

// When sets expectation for the LomsClient.OrderCancel which will trigger the result defined by the following
// Then helper
func (mmOrderCancel *mLomsClientMockOrderCancel) When(ctx context.Context, in *mm_loms.OrderCancelRequest, opts ...grpc.CallOption) *LomsClientMockOrderCancelExpectation {
	if mmOrderCancel.mock.funcOrderCancel != nil {
		mmOrderCancel.mock.t.Fatalf("LomsClientMock.OrderCancel mock is already set by Set")
	}

	expectation := &LomsClientMockOrderCancelExpectation{
		mock:               mmOrderCancel.mock,
		params:             &LomsClientMockOrderCancelParams{ctx, in, opts},
		expectationOrigins: LomsClientMockOrderCancelExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmOrderCancel.expectations = append(mmOrderCancel.expectations, expectation)
	return expectation
}

// Then sets up LomsClient.OrderCancel return parameters for the expectation previously defined by the When method
func (e *LomsClientMockOrderCancelExpectation) Then(ep1 *emptypb.Empty, err error) *LomsClientMock {
	e.results = &LomsClientMockOrderCancelResults{ep1, err}
	return e.mock
}

// Times sets number of times LomsClient.OrderCancel should be invoked
func (mmOrderCancel *mLomsClientMockOrderCancel) Times(n uint64) *mLomsClientMockOrderCancel {
	if n == 0 {
		mmOrderCancel.mock.t.Fatalf("Times of LomsClientMock.OrderCancel mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmOrderCancel.expectedInvocations, n)
	mmOrderCancel.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmOrderCancel
}

func (mmOrderCancel *mLomsClientMockOrderCancel) invocationsDone() bool {
	if len(mmOrderCancel.expectations) == 0 && mmOrderCancel.defaultExpectation == nil && mmOrderCancel.mock.funcOrderCancel == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmOrderCancel.mock.afterOrderCancelCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmOrderCancel.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// OrderCancel implements mm_loms.LomsClient
func (mmOrderCancel *LomsClientMock) OrderCancel(ctx context.Context, in *mm_loms.OrderCancelRequest, opts ...grpc.CallOption) (ep1 *emptypb.Empty, err error) {
	mm_atomic.AddUint64(&mmOrderCancel.beforeOrderCancelCounter, 1)
	defer mm_atomic.AddUint64(&mmOrderCancel.afterOrderCancelCounter, 1)

	mmOrderCancel.t.Helper()

	if mmOrderCancel.inspectFuncOrderCancel != nil {
		mmOrderCancel.inspectFuncOrderCancel(ctx, in, opts...)
	}

	mm_params := LomsClientMockOrderCancelParams{ctx, in, opts}

	// Record call args
	mmOrderCancel.OrderCancelMock.mutex.Lock()
	mmOrderCancel.OrderCancelMock.callArgs = append(mmOrderCancel.OrderCancelMock.callArgs, &mm_params)
	mmOrderCancel.OrderCancelMock.mutex.Unlock()

	for _, e := range mmOrderCancel.OrderCancelMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ep1, e.results.err
		}
	}

	if mmOrderCancel.OrderCancelMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmOrderCancel.OrderCancelMock.defaultExpectation.Counter, 1)
		mm_want := mmOrderCancel.OrderCancelMock.defaultExpectation.params
		mm_want_ptrs := mmOrderCancel.OrderCancelMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockOrderCancelParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmOrderCancel.t.Errorf("LomsClientMock.OrderCancel got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderCancel.OrderCancelMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmOrderCancel.t.Errorf("LomsClientMock.OrderCancel got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderCancel.OrderCancelMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmOrderCancel.t.Errorf("LomsClientMock.OrderCancel got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderCancel.OrderCancelMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmOrderCancel.t.Errorf("LomsClientMock.OrderCancel got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmOrderCancel.OrderCancelMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmOrderCancel.OrderCancelMock.defaultExpectation.results
		if mm_results == nil {
			mmOrderCancel.t.Fatal("No results are set for the LomsClientMock.OrderCancel")
		}
		return (*mm_results).ep1, (*mm_results).err
	}
	if mmOrderCancel.funcOrderCancel != nil {
		return mmOrderCancel.funcOrderCancel(ctx, in, opts...)
	}
	mmOrderCancel.t.Fatalf("Unexpected call to LomsClientMock.OrderCancel. %v %v %v", ctx, in, opts)
	return
}

// OrderCancelAfterCounter returns a count of finished LomsClientMock.OrderCancel invocations
func (mmOrderCancel *LomsClientMock) OrderCancelAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderCancel.afterOrderCancelCounter)
}

// OrderCancelBeforeCounter returns a count of LomsClientMock.OrderCancel invocations
func (mmOrderCancel *LomsClientMock) OrderCancelBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderCancel.beforeOrderCancelCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.OrderCancel.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmOrderCancel *mLomsClientMockOrderCancel) Calls() []*LomsClientMockOrderCancelParams {
	mmOrderCancel.mutex.RLock()

	argCopy := make([]*LomsClientMockOrderCancelParams, len(mmOrderCancel.callArgs))
	copy(argCopy, mmOrderCancel.callArgs)

	mmOrderCancel.mutex.RUnlock()

	return argCopy
}

// MinimockOrderCancelDone returns true if the count of the OrderCancel invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockOrderCancelDone() bool {
	if m.OrderCancelMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.OrderCancelMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.OrderCancelMock.invocationsDone()
}

// MinimockOrderCancelInspect logs each unmet expectation
func (m *LomsClientMock) MinimockOrderCancelInspect() {
	for _, e := range m.OrderCancelMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.OrderCancel at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterOrderCancelCounter := mm_atomic.LoadUint64(&m.afterOrderCancelCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.OrderCancelMock.defaultExpectation != nil && afterOrderCancelCounter < 1 {
		if m.OrderCancelMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.OrderCancel at\n%s", m.OrderCancelMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.OrderCancel at\n%s with params: %#v", m.OrderCancelMock.defaultExpectation.expectationOrigins.origin, *m.OrderCancelMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcOrderCancel != nil && afterOrderCancelCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.OrderCancel at\n%s", m.funcOrderCancelOrigin)
	}

	if !m.OrderCancelMock.invocationsDone() && afterOrderCancelCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.OrderCancel at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.OrderCancelMock.expectedInvocations), m.OrderCancelMock.expectedInvocationsOrigin, afterOrderCancelCounter)
	}
}

type mLomsClientMockOrderCreate struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockOrderCreateExpectation
	expectations       []*LomsClientMockOrderCreateExpectation

	callArgs []*LomsClientMockOrderCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockOrderCreateExpectation specifies expectation struct of the LomsClient.OrderCreate
type LomsClientMockOrderCreateExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockOrderCreateParams
	paramPtrs          *LomsClientMockOrderCreateParamPtrs
	expectationOrigins LomsClientMockOrderCreateExpectationOrigins
	results            *LomsClientMockOrderCreateResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockOrderCreateParams contains parameters of the LomsClient.OrderCreate
type LomsClientMockOrderCreateParams struct {
	ctx  context.Context
	in   *mm_loms.OrderCreateRequest
	opts []grpc.CallOption
}

// LomsClientMockOrderCreateParamPtrs contains pointers to parameters of the LomsClient.OrderCreate
type LomsClientMockOrderCreateParamPtrs struct {
	ctx  *context.Context
	in   **mm_loms.OrderCreateRequest
	opts *[]grpc.CallOption
}

// LomsClientMockOrderCreateResults contains results of the LomsClient.OrderCreate
type LomsClientMockOrderCreateResults struct {
	op1 *mm_loms.OrderCreateResponse
	err error
}

// LomsClientMockOrderCreateOrigins contains origins of expectations of the LomsClient.OrderCreate
type LomsClientMockOrderCreateExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmOrderCreate *mLomsClientMockOrderCreate) Optional() *mLomsClientMockOrderCreate {
	mmOrderCreate.optional = true
	return mmOrderCreate
}

// Expect sets up expected params for LomsClient.OrderCreate
func (mmOrderCreate *mLomsClientMockOrderCreate) Expect(ctx context.Context, in *mm_loms.OrderCreateRequest, opts ...grpc.CallOption) *mLomsClientMockOrderCreate {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsClientMockOrderCreateExpectation{}
	}

	if mmOrderCreate.defaultExpectation.paramPtrs != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by ExpectParams functions")
	}

	mmOrderCreate.defaultExpectation.params = &LomsClientMockOrderCreateParams{ctx, in, opts}
	mmOrderCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmOrderCreate.expectations {
		if minimock.Equal(e.params, mmOrderCreate.defaultExpectation.params) {
			mmOrderCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmOrderCreate.defaultExpectation.params)
		}
	}

	return mmOrderCreate
}

// ExpectCtxParam1 sets up expected param ctx for LomsClient.OrderCreate
func (mmOrderCreate *mLomsClientMockOrderCreate) ExpectCtxParam1(ctx context.Context) *mLomsClientMockOrderCreate {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsClientMockOrderCreateExpectation{}
	}

	if mmOrderCreate.defaultExpectation.params != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by Expect")
	}

	if mmOrderCreate.defaultExpectation.paramPtrs == nil {
		mmOrderCreate.defaultExpectation.paramPtrs = &LomsClientMockOrderCreateParamPtrs{}
	}
	mmOrderCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmOrderCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmOrderCreate
}

// ExpectInParam2 sets up expected param in for LomsClient.OrderCreate
func (mmOrderCreate *mLomsClientMockOrderCreate) ExpectInParam2(in *mm_loms.OrderCreateRequest) *mLomsClientMockOrderCreate {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsClientMockOrderCreateExpectation{}
	}

	if mmOrderCreate.defaultExpectation.params != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by Expect")
	}

	if mmOrderCreate.defaultExpectation.paramPtrs == nil {
		mmOrderCreate.defaultExpectation.paramPtrs = &LomsClientMockOrderCreateParamPtrs{}
	}
	mmOrderCreate.defaultExpectation.paramPtrs.in = &in
	mmOrderCreate.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmOrderCreate
}

// ExpectOptsParam3 sets up expected param opts for LomsClient.OrderCreate
func (mmOrderCreate *mLomsClientMockOrderCreate) ExpectOptsParam3(opts ...grpc.CallOption) *mLomsClientMockOrderCreate {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsClientMockOrderCreateExpectation{}
	}

	if mmOrderCreate.defaultExpectation.params != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by Expect")
	}

	if mmOrderCreate.defaultExpectation.paramPtrs == nil {
		mmOrderCreate.defaultExpectation.paramPtrs = &LomsClientMockOrderCreateParamPtrs{}
	}
	mmOrderCreate.defaultExpectation.paramPtrs.opts = &opts
	mmOrderCreate.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmOrderCreate
}

// Inspect accepts an inspector function that has same arguments as the LomsClient.OrderCreate
func (mmOrderCreate *mLomsClientMockOrderCreate) Inspect(f func(ctx context.Context, in *mm_loms.OrderCreateRequest, opts ...grpc.CallOption)) *mLomsClientMockOrderCreate {
	if mmOrderCreate.mock.inspectFuncOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("Inspect function is already set for LomsClientMock.OrderCreate")
	}

	mmOrderCreate.mock.inspectFuncOrderCreate = f

	return mmOrderCreate
}

// Return sets up results that will be returned by LomsClient.OrderCreate
func (mmOrderCreate *mLomsClientMockOrderCreate) Return(op1 *mm_loms.OrderCreateResponse, err error) *LomsClientMock {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsClientMockOrderCreateExpectation{mock: mmOrderCreate.mock}
	}
	mmOrderCreate.defaultExpectation.results = &LomsClientMockOrderCreateResults{op1, err}
	mmOrderCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmOrderCreate.mock
}

// Set uses given function f to mock the LomsClient.OrderCreate method
func (mmOrderCreate *mLomsClientMockOrderCreate) Set(f func(ctx context.Context, in *mm_loms.OrderCreateRequest, opts ...grpc.CallOption) (op1 *mm_loms.OrderCreateResponse, err error)) *LomsClientMock {
	if mmOrderCreate.defaultExpectation != nil {
		mmOrderCreate.mock.t.Fatalf("Default expectation is already set for the LomsClient.OrderCreate method")
	}

	if len(mmOrderCreate.expectations) > 0 {
		mmOrderCreate.mock.t.Fatalf("Some expectations are already set for the LomsClient.OrderCreate method")
	}

	mmOrderCreate.mock.funcOrderCreate = f
	mmOrderCreate.mock.funcOrderCreateOrigin = minimock.CallerInfo(1)
	return mmOrderCreate.mock
}

// When sets expectation for the LomsClient.OrderCreate which will trigger the result defined by the following
// Then helper
func (mmOrderCreate *mLomsClientMockOrderCreate) When(ctx context.Context, in *mm_loms.OrderCreateRequest, opts ...grpc.CallOption) *LomsClientMockOrderCreateExpectation {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsClientMock.OrderCreate mock is already set by Set")
	}

	expectation := &LomsClientMockOrderCreateExpectation{
		mock:               mmOrderCreate.mock,
		params:             &LomsClientMockOrderCreateParams{ctx, in, opts},
		expectationOrigins: LomsClientMockOrderCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmOrderCreate.expectations = append(mmOrderCreate.expectations, expectation)
	return expectation
}

// Then sets up LomsClient.OrderCreate return parameters for the expectation previously defined by the When method
func (e *LomsClientMockOrderCreateExpectation) Then(op1 *mm_loms.OrderCreateResponse, err error) *LomsClientMock {
	e.results = &LomsClientMockOrderCreateResults{op1, err}
	return e.mock
}

// Times sets number of times LomsClient.OrderCreate should be invoked
func (mmOrderCreate *mLomsClientMockOrderCreate) Times(n uint64) *mLomsClientMockOrderCreate {
	if n == 0 {
		mmOrderCreate.mock.t.Fatalf("Times of LomsClientMock.OrderCreate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmOrderCreate.expectedInvocations, n)
	mmOrderCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmOrderCreate
}

func (mmOrderCreate *mLomsClientMockOrderCreate) invocationsDone() bool {
	if len(mmOrderCreate.expectations) == 0 && mmOrderCreate.defaultExpectation == nil && mmOrderCreate.mock.funcOrderCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmOrderCreate.mock.afterOrderCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmOrderCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// OrderCreate implements mm_loms.LomsClient
func (mmOrderCreate *LomsClientMock) OrderCreate(ctx context.Context, in *mm_loms.OrderCreateRequest, opts ...grpc.CallOption) (op1 *mm_loms.OrderCreateResponse, err error) {
	mm_atomic.AddUint64(&mmOrderCreate.beforeOrderCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmOrderCreate.afterOrderCreateCounter, 1)

	mmOrderCreate.t.Helper()

	if mmOrderCreate.inspectFuncOrderCreate != nil {
		mmOrderCreate.inspectFuncOrderCreate(ctx, in, opts...)
	}

	mm_params := LomsClientMockOrderCreateParams{ctx, in, opts}

	// Record call args
	mmOrderCreate.OrderCreateMock.mutex.Lock()
	mmOrderCreate.OrderCreateMock.callArgs = append(mmOrderCreate.OrderCreateMock.callArgs, &mm_params)
	mmOrderCreate.OrderCreateMock.mutex.Unlock()

	for _, e := range mmOrderCreate.OrderCreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.op1, e.results.err
		}
	}

	if mmOrderCreate.OrderCreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmOrderCreate.OrderCreateMock.defaultExpectation.Counter, 1)
		mm_want := mmOrderCreate.OrderCreateMock.defaultExpectation.params
		mm_want_ptrs := mmOrderCreate.OrderCreateMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockOrderCreateParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmOrderCreate.t.Errorf("LomsClientMock.OrderCreate got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderCreate.OrderCreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmOrderCreate.t.Errorf("LomsClientMock.OrderCreate got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderCreate.OrderCreateMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmOrderCreate.t.Errorf("LomsClientMock.OrderCreate got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderCreate.OrderCreateMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmOrderCreate.t.Errorf("LomsClientMock.OrderCreate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmOrderCreate.OrderCreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmOrderCreate.OrderCreateMock.defaultExpectation.results
		if mm_results == nil {
			mmOrderCreate.t.Fatal("No results are set for the LomsClientMock.OrderCreate")
		}
		return (*mm_results).op1, (*mm_results).err
	}
	if mmOrderCreate.funcOrderCreate != nil {
		return mmOrderCreate.funcOrderCreate(ctx, in, opts...)
	}
	mmOrderCreate.t.Fatalf("Unexpected call to LomsClientMock.OrderCreate. %v %v %v", ctx, in, opts)
	return
}

// OrderCreateAfterCounter returns a count of finished LomsClientMock.OrderCreate invocations
func (mmOrderCreate *LomsClientMock) OrderCreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderCreate.afterOrderCreateCounter)
}

// OrderCreateBeforeCounter returns a count of LomsClientMock.OrderCreate invocations
func (mmOrderCreate *LomsClientMock) OrderCreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderCreate.beforeOrderCreateCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.OrderCreate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmOrderCreate *mLomsClientMockOrderCreate) Calls() []*LomsClientMockOrderCreateParams {
	mmOrderCreate.mutex.RLock()

	argCopy := make([]*LomsClientMockOrderCreateParams, len(mmOrderCreate.callArgs))
	copy(argCopy, mmOrderCreate.callArgs)

	mmOrderCreate.mutex.RUnlock()

	return argCopy
}

// MinimockOrderCreateDone returns true if the count of the OrderCreate invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockOrderCreateDone() bool {
	if m.OrderCreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.OrderCreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.OrderCreateMock.invocationsDone()
}

// MinimockOrderCreateInspect logs each unmet expectation
func (m *LomsClientMock) MinimockOrderCreateInspect() {
	for _, e := range m.OrderCreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.OrderCreate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterOrderCreateCounter := mm_atomic.LoadUint64(&m.afterOrderCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.OrderCreateMock.defaultExpectation != nil && afterOrderCreateCounter < 1 {
		if m.OrderCreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.OrderCreate at\n%s", m.OrderCreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.OrderCreate at\n%s with params: %#v", m.OrderCreateMock.defaultExpectation.expectationOrigins.origin, *m.OrderCreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcOrderCreate != nil && afterOrderCreateCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.OrderCreate at\n%s", m.funcOrderCreateOrigin)
	}

	if !m.OrderCreateMock.invocationsDone() && afterOrderCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.OrderCreate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.OrderCreateMock.expectedInvocations), m.OrderCreateMock.expectedInvocationsOrigin, afterOrderCreateCounter)
	}
}

type mLomsClientMockOrderInfo struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockOrderInfoExpectation
	expectations       []*LomsClientMockOrderInfoExpectation

	callArgs []*LomsClientMockOrderInfoParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockOrderInfoExpectation specifies expectation struct of the LomsClient.OrderInfo
type LomsClientMockOrderInfoExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockOrderInfoParams
	paramPtrs          *LomsClientMockOrderInfoParamPtrs
	expectationOrigins LomsClientMockOrderInfoExpectationOrigins
	results            *LomsClientMockOrderInfoResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockOrderInfoParams contains parameters of the LomsClient.OrderInfo
type LomsClientMockOrderInfoParams struct {
	ctx  context.Context
	in   *mm_loms.OrderInfoRequest
	opts []grpc.CallOption
}

// LomsClientMockOrderInfoParamPtrs contains pointers to parameters of the LomsClient.OrderInfo
type LomsClientMockOrderInfoParamPtrs struct {
	ctx  *context.Context
	in   **mm_loms.OrderInfoRequest
	opts *[]grpc.CallOption
}

// LomsClientMockOrderInfoResults contains results of the LomsClient.OrderInfo
type LomsClientMockOrderInfoResults struct {
	op1 *mm_loms.OrderInfoResponse
	err error
}

// LomsClientMockOrderInfoOrigins contains origins of expectations of the LomsClient.OrderInfo
type LomsClientMockOrderInfoExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmOrderInfo *mLomsClientMockOrderInfo) Optional() *mLomsClientMockOrderInfo {
	mmOrderInfo.optional = true
	return mmOrderInfo
}

// Expect sets up expected params for LomsClient.OrderInfo
func (mmOrderInfo *mLomsClientMockOrderInfo) Expect(ctx context.Context, in *mm_loms.OrderInfoRequest, opts ...grpc.CallOption) *mLomsClientMockOrderInfo {
	if mmOrderInfo.mock.funcOrderInfo != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by Set")
	}

	if mmOrderInfo.defaultExpectation == nil {
		mmOrderInfo.defaultExpectation = &LomsClientMockOrderInfoExpectation{}
	}

	if mmOrderInfo.defaultExpectation.paramPtrs != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by ExpectParams functions")
	}

	mmOrderInfo.defaultExpectation.params = &LomsClientMockOrderInfoParams{ctx, in, opts}
	mmOrderInfo.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmOrderInfo.expectations {
		if minimock.Equal(e.params, mmOrderInfo.defaultExpectation.params) {
			mmOrderInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmOrderInfo.defaultExpectation.params)
		}
	}

	return mmOrderInfo
}

// ExpectCtxParam1 sets up expected param ctx for LomsClient.OrderInfo
func (mmOrderInfo *mLomsClientMockOrderInfo) ExpectCtxParam1(ctx context.Context) *mLomsClientMockOrderInfo {
	if mmOrderInfo.mock.funcOrderInfo != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by Set")
	}

	if mmOrderInfo.defaultExpectation == nil {
		mmOrderInfo.defaultExpectation = &LomsClientMockOrderInfoExpectation{}
	}

	if mmOrderInfo.defaultExpectation.params != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by Expect")
	}

	if mmOrderInfo.defaultExpectation.paramPtrs == nil {
		mmOrderInfo.defaultExpectation.paramPtrs = &LomsClientMockOrderInfoParamPtrs{}
	}
	mmOrderInfo.defaultExpectation.paramPtrs.ctx = &ctx
	mmOrderInfo.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmOrderInfo
}

// ExpectInParam2 sets up expected param in for LomsClient.OrderInfo
func (mmOrderInfo *mLomsClientMockOrderInfo) ExpectInParam2(in *mm_loms.OrderInfoRequest) *mLomsClientMockOrderInfo {
	if mmOrderInfo.mock.funcOrderInfo != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by Set")
	}

	if mmOrderInfo.defaultExpectation == nil {
		mmOrderInfo.defaultExpectation = &LomsClientMockOrderInfoExpectation{}
	}

	if mmOrderInfo.defaultExpectation.params != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by Expect")
	}

	if mmOrderInfo.defaultExpectation.paramPtrs == nil {
		mmOrderInfo.defaultExpectation.paramPtrs = &LomsClientMockOrderInfoParamPtrs{}
	}
	mmOrderInfo.defaultExpectation.paramPtrs.in = &in
	mmOrderInfo.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmOrderInfo
}

// ExpectOptsParam3 sets up expected param opts for LomsClient.OrderInfo
func (mmOrderInfo *mLomsClientMockOrderInfo) ExpectOptsParam3(opts ...grpc.CallOption) *mLomsClientMockOrderInfo {
	if mmOrderInfo.mock.funcOrderInfo != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by Set")
	}

	if mmOrderInfo.defaultExpectation == nil {
		mmOrderInfo.defaultExpectation = &LomsClientMockOrderInfoExpectation{}
	}

	if mmOrderInfo.defaultExpectation.params != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by Expect")
	}

	if mmOrderInfo.defaultExpectation.paramPtrs == nil {
		mmOrderInfo.defaultExpectation.paramPtrs = &LomsClientMockOrderInfoParamPtrs{}
	}
	mmOrderInfo.defaultExpectation.paramPtrs.opts = &opts
	mmOrderInfo.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmOrderInfo
}

// Inspect accepts an inspector function that has same arguments as the LomsClient.OrderInfo
func (mmOrderInfo *mLomsClientMockOrderInfo) Inspect(f func(ctx context.Context, in *mm_loms.OrderInfoRequest, opts ...grpc.CallOption)) *mLomsClientMockOrderInfo {
	if mmOrderInfo.mock.inspectFuncOrderInfo != nil {
		mmOrderInfo.mock.t.Fatalf("Inspect function is already set for LomsClientMock.OrderInfo")
	}

	mmOrderInfo.mock.inspectFuncOrderInfo = f

	return mmOrderInfo
}

// Return sets up results that will be returned by LomsClient.OrderInfo
func (mmOrderInfo *mLomsClientMockOrderInfo) Return(op1 *mm_loms.OrderInfoResponse, err error) *LomsClientMock {
	if mmOrderInfo.mock.funcOrderInfo != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by Set")
	}

	if mmOrderInfo.defaultExpectation == nil {
		mmOrderInfo.defaultExpectation = &LomsClientMockOrderInfoExpectation{mock: mmOrderInfo.mock}
	}
	mmOrderInfo.defaultExpectation.results = &LomsClientMockOrderInfoResults{op1, err}
	mmOrderInfo.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmOrderInfo.mock
}

// Set uses given function f to mock the LomsClient.OrderInfo method
func (mmOrderInfo *mLomsClientMockOrderInfo) Set(f func(ctx context.Context, in *mm_loms.OrderInfoRequest, opts ...grpc.CallOption) (op1 *mm_loms.OrderInfoResponse, err error)) *LomsClientMock {
	if mmOrderInfo.defaultExpectation != nil {
		mmOrderInfo.mock.t.Fatalf("Default expectation is already set for the LomsClient.OrderInfo method")
	}

	if len(mmOrderInfo.expectations) > 0 {
		mmOrderInfo.mock.t.Fatalf("Some expectations are already set for the LomsClient.OrderInfo method")
	}

	mmOrderInfo.mock.funcOrderInfo = f
	mmOrderInfo.mock.funcOrderInfoOrigin = minimock.CallerInfo(1)
	return mmOrderInfo.mock
}

// When sets expectation for the LomsClient.OrderInfo which will trigger the result defined by the following
// Then helper
func (mmOrderInfo *mLomsClientMockOrderInfo) When(ctx context.Context, in *mm_loms.OrderInfoRequest, opts ...grpc.CallOption) *LomsClientMockOrderInfoExpectation {
	if mmOrderInfo.mock.funcOrderInfo != nil {
		mmOrderInfo.mock.t.Fatalf("LomsClientMock.OrderInfo mock is already set by Set")
	}

	expectation := &LomsClientMockOrderInfoExpectation{
		mock:               mmOrderInfo.mock,
		params:             &LomsClientMockOrderInfoParams{ctx, in, opts},
		expectationOrigins: LomsClientMockOrderInfoExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmOrderInfo.expectations = append(mmOrderInfo.expectations, expectation)
	return expectation
}

// Then sets up LomsClient.OrderInfo return parameters for the expectation previously defined by the When method
func (e *LomsClientMockOrderInfoExpectation) Then(op1 *mm_loms.OrderInfoResponse, err error) *LomsClientMock {
	e.results = &LomsClientMockOrderInfoResults{op1, err}
	return e.mock
}

// Times sets number of times LomsClient.OrderInfo should be invoked
func (mmOrderInfo *mLomsClientMockOrderInfo) Times(n uint64) *mLomsClientMockOrderInfo {
	if n == 0 {
		mmOrderInfo.mock.t.Fatalf("Times of LomsClientMock.OrderInfo mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmOrderInfo.expectedInvocations, n)
	mmOrderInfo.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmOrderInfo
}

func (mmOrderInfo *mLomsClientMockOrderInfo) invocationsDone() bool {
	if len(mmOrderInfo.expectations) == 0 && mmOrderInfo.defaultExpectation == nil && mmOrderInfo.mock.funcOrderInfo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmOrderInfo.mock.afterOrderInfoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmOrderInfo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// OrderInfo implements mm_loms.LomsClient
func (mmOrderInfo *LomsClientMock) OrderInfo(ctx context.Context, in *mm_loms.OrderInfoRequest, opts ...grpc.CallOption) (op1 *mm_loms.OrderInfoResponse, err error) {
	mm_atomic.AddUint64(&mmOrderInfo.beforeOrderInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmOrderInfo.afterOrderInfoCounter, 1)

	mmOrderInfo.t.Helper()

	if mmOrderInfo.inspectFuncOrderInfo != nil {
		mmOrderInfo.inspectFuncOrderInfo(ctx, in, opts...)
	}

	mm_params := LomsClientMockOrderInfoParams{ctx, in, opts}

	// Record call args
	mmOrderInfo.OrderInfoMock.mutex.Lock()
	mmOrderInfo.OrderInfoMock.callArgs = append(mmOrderInfo.OrderInfoMock.callArgs, &mm_params)
	mmOrderInfo.OrderInfoMock.mutex.Unlock()

	for _, e := range mmOrderInfo.OrderInfoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.op1, e.results.err
		}
	}

	if mmOrderInfo.OrderInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmOrderInfo.OrderInfoMock.defaultExpectation.Counter, 1)
		mm_want := mmOrderInfo.OrderInfoMock.defaultExpectation.params
		mm_want_ptrs := mmOrderInfo.OrderInfoMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockOrderInfoParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmOrderInfo.t.Errorf("LomsClientMock.OrderInfo got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderInfo.OrderInfoMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmOrderInfo.t.Errorf("LomsClientMock.OrderInfo got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderInfo.OrderInfoMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmOrderInfo.t.Errorf("LomsClientMock.OrderInfo got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderInfo.OrderInfoMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmOrderInfo.t.Errorf("LomsClientMock.OrderInfo got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmOrderInfo.OrderInfoMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmOrderInfo.OrderInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmOrderInfo.t.Fatal("No results are set for the LomsClientMock.OrderInfo")
		}
		return (*mm_results).op1, (*mm_results).err
	}
	if mmOrderInfo.funcOrderInfo != nil {
		return mmOrderInfo.funcOrderInfo(ctx, in, opts...)
	}
	mmOrderInfo.t.Fatalf("Unexpected call to LomsClientMock.OrderInfo. %v %v %v", ctx, in, opts)
	return
}

// OrderInfoAfterCounter returns a count of finished LomsClientMock.OrderInfo invocations
func (mmOrderInfo *LomsClientMock) OrderInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderInfo.afterOrderInfoCounter)
}

// OrderInfoBeforeCounter returns a count of LomsClientMock.OrderInfo invocations
func (mmOrderInfo *LomsClientMock) OrderInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderInfo.beforeOrderInfoCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.OrderInfo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmOrderInfo *mLomsClientMockOrderInfo) Calls() []*LomsClientMockOrderInfoParams {
	mmOrderInfo.mutex.RLock()

	argCopy := make([]*LomsClientMockOrderInfoParams, len(mmOrderInfo.callArgs))
	copy(argCopy, mmOrderInfo.callArgs)

	mmOrderInfo.mutex.RUnlock()

	return argCopy
}

// MinimockOrderInfoDone returns true if the count of the OrderInfo invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockOrderInfoDone() bool {
	if m.OrderInfoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.OrderInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.OrderInfoMock.invocationsDone()
}

// MinimockOrderInfoInspect logs each unmet expectation
func (m *LomsClientMock) MinimockOrderInfoInspect() {
	for _, e := range m.OrderInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.OrderInfo at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterOrderInfoCounter := mm_atomic.LoadUint64(&m.afterOrderInfoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.OrderInfoMock.defaultExpectation != nil && afterOrderInfoCounter < 1 {
		if m.OrderInfoMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.OrderInfo at\n%s", m.OrderInfoMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.OrderInfo at\n%s with params: %#v", m.OrderInfoMock.defaultExpectation.expectationOrigins.origin, *m.OrderInfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcOrderInfo != nil && afterOrderInfoCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.OrderInfo at\n%s", m.funcOrderInfoOrigin)
	}

	if !m.OrderInfoMock.invocationsDone() && afterOrderInfoCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.OrderInfo at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.OrderInfoMock.expectedInvocations), m.OrderInfoMock.expectedInvocationsOrigin, afterOrderInfoCounter)
	}
}

type mLomsClientMockOrderPay struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockOrderPayExpectation
	expectations       []*LomsClientMockOrderPayExpectation

	callArgs []*LomsClientMockOrderPayParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockOrderPayExpectation specifies expectation struct of the LomsClient.OrderPay
type LomsClientMockOrderPayExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockOrderPayParams
	paramPtrs          *LomsClientMockOrderPayParamPtrs
	expectationOrigins LomsClientMockOrderPayExpectationOrigins
	results            *LomsClientMockOrderPayResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockOrderPayParams contains parameters of the LomsClient.OrderPay
type LomsClientMockOrderPayParams struct {
	ctx  context.Context
	in   *mm_loms.OrderPayRequest
	opts []grpc.CallOption
}

// LomsClientMockOrderPayParamPtrs contains pointers to parameters of the LomsClient.OrderPay
type LomsClientMockOrderPayParamPtrs struct {
	ctx  *context.Context
	in   **mm_loms.OrderPayRequest
	opts *[]grpc.CallOption
}

// LomsClientMockOrderPayResults contains results of the LomsClient.OrderPay
type LomsClientMockOrderPayResults struct {
	ep1 *emptypb.Empty
	err error
}

// LomsClientMockOrderPayOrigins contains origins of expectations of the LomsClient.OrderPay
type LomsClientMockOrderPayExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmOrderPay *mLomsClientMockOrderPay) Optional() *mLomsClientMockOrderPay {
	mmOrderPay.optional = true
	return mmOrderPay
}

// Expect sets up expected params for LomsClient.OrderPay
func (mmOrderPay *mLomsClientMockOrderPay) Expect(ctx context.Context, in *mm_loms.OrderPayRequest, opts ...grpc.CallOption) *mLomsClientMockOrderPay {
	if mmOrderPay.mock.funcOrderPay != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by Set")
	}

	if mmOrderPay.defaultExpectation == nil {
		mmOrderPay.defaultExpectation = &LomsClientMockOrderPayExpectation{}
	}

	if mmOrderPay.defaultExpectation.paramPtrs != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by ExpectParams functions")
	}

	mmOrderPay.defaultExpectation.params = &LomsClientMockOrderPayParams{ctx, in, opts}
	mmOrderPay.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmOrderPay.expectations {
		if minimock.Equal(e.params, mmOrderPay.defaultExpectation.params) {
			mmOrderPay.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmOrderPay.defaultExpectation.params)
		}
	}

	return mmOrderPay
}

// ExpectCtxParam1 sets up expected param ctx for LomsClient.OrderPay
func (mmOrderPay *mLomsClientMockOrderPay) ExpectCtxParam1(ctx context.Context) *mLomsClientMockOrderPay {
	if mmOrderPay.mock.funcOrderPay != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by Set")
	}

	if mmOrderPay.defaultExpectation == nil {
		mmOrderPay.defaultExpectation = &LomsClientMockOrderPayExpectation{}
	}

	if mmOrderPay.defaultExpectation.params != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by Expect")
	}

	if mmOrderPay.defaultExpectation.paramPtrs == nil {
		mmOrderPay.defaultExpectation.paramPtrs = &LomsClientMockOrderPayParamPtrs{}
	}
	mmOrderPay.defaultExpectation.paramPtrs.ctx = &ctx
	mmOrderPay.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmOrderPay
}

// ExpectInParam2 sets up expected param in for LomsClient.OrderPay
func (mmOrderPay *mLomsClientMockOrderPay) ExpectInParam2(in *mm_loms.OrderPayRequest) *mLomsClientMockOrderPay {
	if mmOrderPay.mock.funcOrderPay != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by Set")
	}

	if mmOrderPay.defaultExpectation == nil {
		mmOrderPay.defaultExpectation = &LomsClientMockOrderPayExpectation{}
	}

	if mmOrderPay.defaultExpectation.params != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by Expect")
	}

	if mmOrderPay.defaultExpectation.paramPtrs == nil {
		mmOrderPay.defaultExpectation.paramPtrs = &LomsClientMockOrderPayParamPtrs{}
	}
	mmOrderPay.defaultExpectation.paramPtrs.in = &in
	mmOrderPay.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmOrderPay
}

// ExpectOptsParam3 sets up expected param opts for LomsClient.OrderPay
func (mmOrderPay *mLomsClientMockOrderPay) ExpectOptsParam3(opts ...grpc.CallOption) *mLomsClientMockOrderPay {
	if mmOrderPay.mock.funcOrderPay != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by Set")
	}

	if mmOrderPay.defaultExpectation == nil {
		mmOrderPay.defaultExpectation = &LomsClientMockOrderPayExpectation{}
	}

	if mmOrderPay.defaultExpectation.params != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by Expect")
	}

	if mmOrderPay.defaultExpectation.paramPtrs == nil {
		mmOrderPay.defaultExpectation.paramPtrs = &LomsClientMockOrderPayParamPtrs{}
	}
	mmOrderPay.defaultExpectation.paramPtrs.opts = &opts
	mmOrderPay.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmOrderPay
}

// Inspect accepts an inspector function that has same arguments as the LomsClient.OrderPay
func (mmOrderPay *mLomsClientMockOrderPay) Inspect(f func(ctx context.Context, in *mm_loms.OrderPayRequest, opts ...grpc.CallOption)) *mLomsClientMockOrderPay {
	if mmOrderPay.mock.inspectFuncOrderPay != nil {
		mmOrderPay.mock.t.Fatalf("Inspect function is already set for LomsClientMock.OrderPay")
	}

	mmOrderPay.mock.inspectFuncOrderPay = f

	return mmOrderPay
}

// Return sets up results that will be returned by LomsClient.OrderPay
func (mmOrderPay *mLomsClientMockOrderPay) Return(ep1 *emptypb.Empty, err error) *LomsClientMock {
	if mmOrderPay.mock.funcOrderPay != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by Set")
	}

	if mmOrderPay.defaultExpectation == nil {
		mmOrderPay.defaultExpectation = &LomsClientMockOrderPayExpectation{mock: mmOrderPay.mock}
	}
	mmOrderPay.defaultExpectation.results = &LomsClientMockOrderPayResults{ep1, err}
	mmOrderPay.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmOrderPay.mock
}

// Set uses given function f to mock the LomsClient.OrderPay method
func (mmOrderPay *mLomsClientMockOrderPay) Set(f func(ctx context.Context, in *mm_loms.OrderPayRequest, opts ...grpc.CallOption) (ep1 *emptypb.Empty, err error)) *LomsClientMock {
	if mmOrderPay.defaultExpectation != nil {
		mmOrderPay.mock.t.Fatalf("Default expectation is already set for the LomsClient.OrderPay method")
	}

	if len(mmOrderPay.expectations) > 0 {
		mmOrderPay.mock.t.Fatalf("Some expectations are already set for the LomsClient.OrderPay method")
	}

	mmOrderPay.mock.funcOrderPay = f
	mmOrderPay.mock.funcOrderPayOrigin = minimock.CallerInfo(1)
	return mmOrderPay.mock
}

// When sets expectation for the LomsClient.OrderPay which will trigger the result defined by the following
// Then helper
func (mmOrderPay *mLomsClientMockOrderPay) When(ctx context.Context, in *mm_loms.OrderPayRequest, opts ...grpc.CallOption) *LomsClientMockOrderPayExpectation {
	if mmOrderPay.mock.funcOrderPay != nil {
		mmOrderPay.mock.t.Fatalf("LomsClientMock.OrderPay mock is already set by Set")
	}

	expectation := &LomsClientMockOrderPayExpectation{
		mock:               mmOrderPay.mock,
		params:             &LomsClientMockOrderPayParams{ctx, in, opts},
		expectationOrigins: LomsClientMockOrderPayExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmOrderPay.expectations = append(mmOrderPay.expectations, expectation)
	return expectation
}

// Then sets up LomsClient.OrderPay return parameters for the expectation previously defined by the When method
func (e *LomsClientMockOrderPayExpectation) Then(ep1 *emptypb.Empty, err error) *LomsClientMock {
	e.results = &LomsClientMockOrderPayResults{ep1, err}
	return e.mock
}

// Times sets number of times LomsClient.OrderPay should be invoked
func (mmOrderPay *mLomsClientMockOrderPay) Times(n uint64) *mLomsClientMockOrderPay {
	if n == 0 {
		mmOrderPay.mock.t.Fatalf("Times of LomsClientMock.OrderPay mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmOrderPay.expectedInvocations, n)
	mmOrderPay.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmOrderPay
}

func (mmOrderPay *mLomsClientMockOrderPay) invocationsDone() bool {
	if len(mmOrderPay.expectations) == 0 && mmOrderPay.defaultExpectation == nil && mmOrderPay.mock.funcOrderPay == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmOrderPay.mock.afterOrderPayCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmOrderPay.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// OrderPay implements mm_loms.LomsClient
func (mmOrderPay *LomsClientMock) OrderPay(ctx context.Context, in *mm_loms.OrderPayRequest, opts ...grpc.CallOption) (ep1 *emptypb.Empty, err error) {
	mm_atomic.AddUint64(&mmOrderPay.beforeOrderPayCounter, 1)
	defer mm_atomic.AddUint64(&mmOrderPay.afterOrderPayCounter, 1)

	mmOrderPay.t.Helper()

	if mmOrderPay.inspectFuncOrderPay != nil {
		mmOrderPay.inspectFuncOrderPay(ctx, in, opts...)
	}

	mm_params := LomsClientMockOrderPayParams{ctx, in, opts}

	// Record call args
	mmOrderPay.OrderPayMock.mutex.Lock()
	mmOrderPay.OrderPayMock.callArgs = append(mmOrderPay.OrderPayMock.callArgs, &mm_params)
	mmOrderPay.OrderPayMock.mutex.Unlock()

	for _, e := range mmOrderPay.OrderPayMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ep1, e.results.err
		}
	}

	if mmOrderPay.OrderPayMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmOrderPay.OrderPayMock.defaultExpectation.Counter, 1)
		mm_want := mmOrderPay.OrderPayMock.defaultExpectation.params
		mm_want_ptrs := mmOrderPay.OrderPayMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockOrderPayParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmOrderPay.t.Errorf("LomsClientMock.OrderPay got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderPay.OrderPayMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmOrderPay.t.Errorf("LomsClientMock.OrderPay got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderPay.OrderPayMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmOrderPay.t.Errorf("LomsClientMock.OrderPay got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderPay.OrderPayMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmOrderPay.t.Errorf("LomsClientMock.OrderPay got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmOrderPay.OrderPayMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmOrderPay.OrderPayMock.defaultExpectation.results
		if mm_results == nil {
			mmOrderPay.t.Fatal("No results are set for the LomsClientMock.OrderPay")
		}
		return (*mm_results).ep1, (*mm_results).err
	}
	if mmOrderPay.funcOrderPay != nil {
		return mmOrderPay.funcOrderPay(ctx, in, opts...)
	}
	mmOrderPay.t.Fatalf("Unexpected call to LomsClientMock.OrderPay. %v %v %v", ctx, in, opts)
	return
}

// OrderPayAfterCounter returns a count of finished LomsClientMock.OrderPay invocations
func (mmOrderPay *LomsClientMock) OrderPayAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderPay.afterOrderPayCounter)
}

// OrderPayBeforeCounter returns a count of LomsClientMock.OrderPay invocations
func (mmOrderPay *LomsClientMock) OrderPayBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderPay.beforeOrderPayCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.OrderPay.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmOrderPay *mLomsClientMockOrderPay) Calls() []*LomsClientMockOrderPayParams {
	mmOrderPay.mutex.RLock()

	argCopy := make([]*LomsClientMockOrderPayParams, len(mmOrderPay.callArgs))
	copy(argCopy, mmOrderPay.callArgs)

	mmOrderPay.mutex.RUnlock()

	return argCopy
}

// MinimockOrderPayDone returns true if the count of the OrderPay invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockOrderPayDone() bool {
	if m.OrderPayMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.OrderPayMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.OrderPayMock.invocationsDone()
}

// MinimockOrderPayInspect logs each unmet expectation
func (m *LomsClientMock) MinimockOrderPayInspect() {
	for _, e := range m.OrderPayMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.OrderPay at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterOrderPayCounter := mm_atomic.LoadUint64(&m.afterOrderPayCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.OrderPayMock.defaultExpectation != nil && afterOrderPayCounter < 1 {
		if m.OrderPayMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.OrderPay at\n%s", m.OrderPayMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.OrderPay at\n%s with params: %#v", m.OrderPayMock.defaultExpectation.expectationOrigins.origin, *m.OrderPayMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcOrderPay != nil && afterOrderPayCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.OrderPay at\n%s", m.funcOrderPayOrigin)
	}

	if !m.OrderPayMock.invocationsDone() && afterOrderPayCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.OrderPay at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.OrderPayMock.expectedInvocations), m.OrderPayMock.expectedInvocationsOrigin, afterOrderPayCounter)
	}
}

type mLomsClientMockStocksInfo struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockStocksInfoExpectation
	expectations       []*LomsClientMockStocksInfoExpectation

	callArgs []*LomsClientMockStocksInfoParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockStocksInfoExpectation specifies expectation struct of the LomsClient.StocksInfo
type LomsClientMockStocksInfoExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockStocksInfoParams
	paramPtrs          *LomsClientMockStocksInfoParamPtrs
	expectationOrigins LomsClientMockStocksInfoExpectationOrigins
	results            *LomsClientMockStocksInfoResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockStocksInfoParams contains parameters of the LomsClient.StocksInfo
type LomsClientMockStocksInfoParams struct {
	ctx  context.Context
	in   *mm_loms.StocksInfoRequest
	opts []grpc.CallOption
}

// LomsClientMockStocksInfoParamPtrs contains pointers to parameters of the LomsClient.StocksInfo
type LomsClientMockStocksInfoParamPtrs struct {
	ctx  *context.Context
	in   **mm_loms.StocksInfoRequest
	opts *[]grpc.CallOption
}

// LomsClientMockStocksInfoResults contains results of the LomsClient.StocksInfo
type LomsClientMockStocksInfoResults struct {
	sp1 *mm_loms.StocksInfoResponse
	err error
}

// LomsClientMockStocksInfoOrigins contains origins of expectations of the LomsClient.StocksInfo
type LomsClientMockStocksInfoExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStocksInfo *mLomsClientMockStocksInfo) Optional() *mLomsClientMockStocksInfo {
	mmStocksInfo.optional = true
	return mmStocksInfo
}

// Expect sets up expected params for LomsClient.StocksInfo
func (mmStocksInfo *mLomsClientMockStocksInfo) Expect(ctx context.Context, in *mm_loms.StocksInfoRequest, opts ...grpc.CallOption) *mLomsClientMockStocksInfo {
	if mmStocksInfo.mock.funcStocksInfo != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by Set")
	}

	if mmStocksInfo.defaultExpectation == nil {
		mmStocksInfo.defaultExpectation = &LomsClientMockStocksInfoExpectation{}
	}

	if mmStocksInfo.defaultExpectation.paramPtrs != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by ExpectParams functions")
	}

	mmStocksInfo.defaultExpectation.params = &LomsClientMockStocksInfoParams{ctx, in, opts}
	mmStocksInfo.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStocksInfo.expectations {
		if minimock.Equal(e.params, mmStocksInfo.defaultExpectation.params) {
			mmStocksInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStocksInfo.defaultExpectation.params)
		}
	}

	return mmStocksInfo
}

// ExpectCtxParam1 sets up expected param ctx for LomsClient.StocksInfo
func (mmStocksInfo *mLomsClientMockStocksInfo) ExpectCtxParam1(ctx context.Context) *mLomsClientMockStocksInfo {
	if mmStocksInfo.mock.funcStocksInfo != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by Set")
	}

	if mmStocksInfo.defaultExpectation == nil {
		mmStocksInfo.defaultExpectation = &LomsClientMockStocksInfoExpectation{}
	}

	if mmStocksInfo.defaultExpectation.params != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by Expect")
	}

	if mmStocksInfo.defaultExpectation.paramPtrs == nil {
		mmStocksInfo.defaultExpectation.paramPtrs = &LomsClientMockStocksInfoParamPtrs{}
	}
	mmStocksInfo.defaultExpectation.paramPtrs.ctx = &ctx
	mmStocksInfo.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStocksInfo
}

// ExpectInParam2 sets up expected param in for LomsClient.StocksInfo
func (mmStocksInfo *mLomsClientMockStocksInfo) ExpectInParam2(in *mm_loms.StocksInfoRequest) *mLomsClientMockStocksInfo {
	if mmStocksInfo.mock.funcStocksInfo != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by Set")
	}

	if mmStocksInfo.defaultExpectation == nil {
		mmStocksInfo.defaultExpectation = &LomsClientMockStocksInfoExpectation{}
	}

	if mmStocksInfo.defaultExpectation.params != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by Expect")
	}

	if mmStocksInfo.defaultExpectation.paramPtrs == nil {
		mmStocksInfo.defaultExpectation.paramPtrs = &LomsClientMockStocksInfoParamPtrs{}
	}
	mmStocksInfo.defaultExpectation.paramPtrs.in = &in
	mmStocksInfo.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmStocksInfo
}

// ExpectOptsParam3 sets up expected param opts for LomsClient.StocksInfo
func (mmStocksInfo *mLomsClientMockStocksInfo) ExpectOptsParam3(opts ...grpc.CallOption) *mLomsClientMockStocksInfo {
	if mmStocksInfo.mock.funcStocksInfo != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by Set")
	}

	if mmStocksInfo.defaultExpectation == nil {
		mmStocksInfo.defaultExpectation = &LomsClientMockStocksInfoExpectation{}
	}

	if mmStocksInfo.defaultExpectation.params != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by Expect")
	}

	if mmStocksInfo.defaultExpectation.paramPtrs == nil {
		mmStocksInfo.defaultExpectation.paramPtrs = &LomsClientMockStocksInfoParamPtrs{}
	}
	mmStocksInfo.defaultExpectation.paramPtrs.opts = &opts
	mmStocksInfo.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmStocksInfo
}

// Inspect accepts an inspector function that has same arguments as the LomsClient.StocksInfo
func (mmStocksInfo *mLomsClientMockStocksInfo) Inspect(f func(ctx context.Context, in *mm_loms.StocksInfoRequest, opts ...grpc.CallOption)) *mLomsClientMockStocksInfo {
	if mmStocksInfo.mock.inspectFuncStocksInfo != nil {
		mmStocksInfo.mock.t.Fatalf("Inspect function is already set for LomsClientMock.StocksInfo")
	}

	mmStocksInfo.mock.inspectFuncStocksInfo = f

	return mmStocksInfo
}

// Return sets up results that will be returned by LomsClient.StocksInfo
func (mmStocksInfo *mLomsClientMockStocksInfo) Return(sp1 *mm_loms.StocksInfoResponse, err error) *LomsClientMock {
	if mmStocksInfo.mock.funcStocksInfo != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by Set")
	}

	if mmStocksInfo.defaultExpectation == nil {
		mmStocksInfo.defaultExpectation = &LomsClientMockStocksInfoExpectation{mock: mmStocksInfo.mock}
	}
	mmStocksInfo.defaultExpectation.results = &LomsClientMockStocksInfoResults{sp1, err}
	mmStocksInfo.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStocksInfo.mock
}

// Set uses given function f to mock the LomsClient.StocksInfo method
func (mmStocksInfo *mLomsClientMockStocksInfo) Set(f func(ctx context.Context, in *mm_loms.StocksInfoRequest, opts ...grpc.CallOption) (sp1 *mm_loms.StocksInfoResponse, err error)) *LomsClientMock {
	if mmStocksInfo.defaultExpectation != nil {
		mmStocksInfo.mock.t.Fatalf("Default expectation is already set for the LomsClient.StocksInfo method")
	}

	if len(mmStocksInfo.expectations) > 0 {
		mmStocksInfo.mock.t.Fatalf("Some expectations are already set for the LomsClient.StocksInfo method")
	}

	mmStocksInfo.mock.funcStocksInfo = f
	mmStocksInfo.mock.funcStocksInfoOrigin = minimock.CallerInfo(1)
	return mmStocksInfo.mock
}

// When sets expectation for the LomsClient.StocksInfo which will trigger the result defined by the following
// Then helper
func (mmStocksInfo *mLomsClientMockStocksInfo) When(ctx context.Context, in *mm_loms.StocksInfoRequest, opts ...grpc.CallOption) *LomsClientMockStocksInfoExpectation {
	if mmStocksInfo.mock.funcStocksInfo != nil {
		mmStocksInfo.mock.t.Fatalf("LomsClientMock.StocksInfo mock is already set by Set")
	}

	expectation := &LomsClientMockStocksInfoExpectation{
		mock:               mmStocksInfo.mock,
		params:             &LomsClientMockStocksInfoParams{ctx, in, opts},
		expectationOrigins: LomsClientMockStocksInfoExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStocksInfo.expectations = append(mmStocksInfo.expectations, expectation)
	return expectation
}

// Then sets up LomsClient.StocksInfo return parameters for the expectation previously defined by the When method
func (e *LomsClientMockStocksInfoExpectation) Then(sp1 *mm_loms.StocksInfoResponse, err error) *LomsClientMock {
	e.results = &LomsClientMockStocksInfoResults{sp1, err}
	return e.mock
}

// Times sets number of times LomsClient.StocksInfo should be invoked
func (mmStocksInfo *mLomsClientMockStocksInfo) Times(n uint64) *mLomsClientMockStocksInfo {
	if n == 0 {
		mmStocksInfo.mock.t.Fatalf("Times of LomsClientMock.StocksInfo mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStocksInfo.expectedInvocations, n)
	mmStocksInfo.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStocksInfo
}

func (mmStocksInfo *mLomsClientMockStocksInfo) invocationsDone() bool {
	if len(mmStocksInfo.expectations) == 0 && mmStocksInfo.defaultExpectation == nil && mmStocksInfo.mock.funcStocksInfo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStocksInfo.mock.afterStocksInfoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStocksInfo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// StocksInfo implements mm_loms.LomsClient
func (mmStocksInfo *LomsClientMock) StocksInfo(ctx context.Context, in *mm_loms.StocksInfoRequest, opts ...grpc.CallOption) (sp1 *mm_loms.StocksInfoResponse, err error) {
	mm_atomic.AddUint64(&mmStocksInfo.beforeStocksInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmStocksInfo.afterStocksInfoCounter, 1)

	mmStocksInfo.t.Helper()

	if mmStocksInfo.inspectFuncStocksInfo != nil {
		mmStocksInfo.inspectFuncStocksInfo(ctx, in, opts...)
	}

	mm_params := LomsClientMockStocksInfoParams{ctx, in, opts}

	// Record call args
	mmStocksInfo.StocksInfoMock.mutex.Lock()
	mmStocksInfo.StocksInfoMock.callArgs = append(mmStocksInfo.StocksInfoMock.callArgs, &mm_params)
	mmStocksInfo.StocksInfoMock.mutex.Unlock()

	for _, e := range mmStocksInfo.StocksInfoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmStocksInfo.StocksInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStocksInfo.StocksInfoMock.defaultExpectation.Counter, 1)
		mm_want := mmStocksInfo.StocksInfoMock.defaultExpectation.params
		mm_want_ptrs := mmStocksInfo.StocksInfoMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockStocksInfoParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStocksInfo.t.Errorf("LomsClientMock.StocksInfo got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStocksInfo.StocksInfoMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmStocksInfo.t.Errorf("LomsClientMock.StocksInfo got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStocksInfo.StocksInfoMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmStocksInfo.t.Errorf("LomsClientMock.StocksInfo got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStocksInfo.StocksInfoMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStocksInfo.t.Errorf("LomsClientMock.StocksInfo got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStocksInfo.StocksInfoMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStocksInfo.StocksInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmStocksInfo.t.Fatal("No results are set for the LomsClientMock.StocksInfo")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmStocksInfo.funcStocksInfo != nil {
		return mmStocksInfo.funcStocksInfo(ctx, in, opts...)
	}
	mmStocksInfo.t.Fatalf("Unexpected call to LomsClientMock.StocksInfo. %v %v %v", ctx, in, opts)
	return
}

// StocksInfoAfterCounter returns a count of finished LomsClientMock.StocksInfo invocations
func (mmStocksInfo *LomsClientMock) StocksInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocksInfo.afterStocksInfoCounter)
}

// StocksInfoBeforeCounter returns a count of LomsClientMock.StocksInfo invocations
func (mmStocksInfo *LomsClientMock) StocksInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocksInfo.beforeStocksInfoCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.StocksInfo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStocksInfo *mLomsClientMockStocksInfo) Calls() []*LomsClientMockStocksInfoParams {
	mmStocksInfo.mutex.RLock()

	argCopy := make([]*LomsClientMockStocksInfoParams, len(mmStocksInfo.callArgs))
	copy(argCopy, mmStocksInfo.callArgs)

	mmStocksInfo.mutex.RUnlock()

	return argCopy
}

// MinimockStocksInfoDone returns true if the count of the StocksInfo invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockStocksInfoDone() bool {
	if m.StocksInfoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StocksInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StocksInfoMock.invocationsDone()
}

// MinimockStocksInfoInspect logs each unmet expectation
func (m *LomsClientMock) MinimockStocksInfoInspect() {
	for _, e := range m.StocksInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.StocksInfo at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStocksInfoCounter := mm_atomic.LoadUint64(&m.afterStocksInfoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StocksInfoMock.defaultExpectation != nil && afterStocksInfoCounter < 1 {
		if m.StocksInfoMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.StocksInfo at\n%s", m.StocksInfoMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.StocksInfo at\n%s with params: %#v", m.StocksInfoMock.defaultExpectation.expectationOrigins.origin, *m.StocksInfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocksInfo != nil && afterStocksInfoCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.StocksInfo at\n%s", m.funcStocksInfoOrigin)
	}

	if !m.StocksInfoMock.invocationsDone() && afterStocksInfoCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.StocksInfo at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StocksInfoMock.expectedInvocations), m.StocksInfoMock.expectedInvocationsOrigin, afterStocksInfoCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LomsClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockOrderCancelInspect()

			m.MinimockOrderCreateInspect()

			m.MinimockOrderInfoInspect()

			m.MinimockOrderPayInspect()

			m.MinimockStocksInfoInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LomsClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LomsClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockOrderCancelDone() &&
		m.MinimockOrderCreateDone() &&
		m.MinimockOrderInfoDone() &&
		m.MinimockOrderPayDone() &&
		m.MinimockStocksInfoDone()
}
