version: "3.8"

services:
  cart:
    container_name: cart
    build: ./cart/
    ports:
      - "8082:8082"
    depends_on:
      - loms
    environment:
      - LOMS_BASE_URL=loms:50051
      - SWAGGER_URL=http://localhost:8080

  loms:
    container_name: loms
    build: ./loms/
    ports:
      - "50051:50051"
      - "8081:8081"
    environment:
        - SWAGGER_FOR_CORS_ALLOWED_URL=http://localhost:8080

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./loms/api/openapiv2/loms.swagger.json:/app/swagger.json
    environment:
      - SWAGGER_JSON=/app/swagger.json
    depends_on:
      - loms
  
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  pgdata:
