version: "3.8"

services:
  cart:
    container_name: cart
    build: ./cart/
    ports:
      - "8082:8082"
    depends_on:
      - loms
    environment:
      - LOMS_BASE_URL=loms:50051
      - SWAGGER_URL=http://localhost:8080

  loms:
    container_name: loms
    build: ./loms/
    ports:
      - "50051:50051"
      - "8081:8081"
    environment:
      - DATABASE_MASTER_HOST_PORT=postgres_master:5432
      - DATABASE_REPLICA_HOST_PORT=postgres_slave:5432
      - SWAGGER_FOR_CORS_ALLOWED_URL=http://localhost:8080

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./loms/api/openapiv2/loms.swagger.json:/app/swagger.json
    environment:
      - SWAGGER_JSON=/app/swagger.json
    depends_on:
      - loms
  
  postgres_master:
    image: postgres:16
    volumes:
      - pgdata_master:/var/lib/postgresql/data
      - ./config/master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/master/pg_hba.conf:/etc/postgresql/data/pg_hba.conf
      - ./config/master/init-script.sh:/docker-entrypoint-initdb.d/init-script.sh
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: ${POSTGRES_MASTER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MASTER_PASSWORD}
      POSTGRES_REPLICA_USER: ${POSTGRES_REPLICA_USER}
      POSTGRES_REPLICA_PASSWORD: ${POSTGRES_REPLICA_PASSWORD}
      
  postgres_slave:
    user: postgres
    image: postgres:16
    volumes:
      - pgdata_slave:/var/lib/postgresql/data
      - ./config/slave/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5433:5432"
    depends_on:
      - postgres_master
    command: >
      bash -c "
      chmod 700 /var/lib/postgresql/data;
      until PGPASSWORD=${POSTGRES_REPLICA_PASSWORD} pg_basebackup -h postgres_master -D /var/lib/postgresql/data -U ${POSTGRES_REPLICA_USER} -Fp -Xs -P -R;
      do
        echo 'Waiting for master to be ready...';
        sleep 1;
      done;
      
      postgres -c config_file=/etc/postgresql/postgresql.conf
      "

volumes:
  pgdata_master:
  pgdata_slave:
