// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package orderrepository

import (
	"context"
)

type Querier interface {
	GetAllOrders(ctx context.Context) ([]*GetAllOrdersRow, error)
	GetOrderById(ctx context.Context, orderID int64) ([]*GetOrderByIdRow, error)
	SaveItems(ctx context.Context, arg *SaveItemsParams) error
	SaveOrder(ctx context.Context, arg *SaveOrderParams) (int64, error)
	UpdateOrder(ctx context.Context, arg *UpdateOrderParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
