// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package outboxrepository

import (
	"context"
)

type Querier interface {
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]*GetPendingOutboxEventsRow, error)
	MarkOutboxEventProcessed(ctx context.Context, id int32) error
	SaveOutboxEvent(ctx context.Context, arg *SaveOutboxEventParams) error
}

var _ Querier = (*Queries)(nil)
